// AUTO-GENERATED by `ondajs add` — do not edit manually.
// Re-run `bunx ondajs add <slug>` to update.
// Pass `--no-barrel` to opt out; delete this file + .ondajs-installed.json
// to disable barrel management going forward.

import { BarChart, barChartSchema } from './bar-chart/BarChart';
import { BrowserFrame, browserFrameSchema } from './browser-frame/BrowserFrame';
import { Confetti, confettiSchema } from './confetti/Confetti';
import { CountUp, countUpSchema } from './count-up/CountUp';
import { Cursor, cursorSchema } from './cursor/Cursor';
import { DeviceFrame, deviceFrameSchema } from './device-frame/DeviceFrame';
import { DrawOn, drawOnSchema } from './draw-on/DrawOn';
import { IconPop, iconPopSchema } from './icon-pop/IconPop';
import { MeshGradient, meshGradientSchema } from './mesh-gradient/MeshGradient';
import { SlotMachineRoll, slotMachineRollSchema } from './slot-machine-roll/SlotMachineRoll';
import { StatCard, statCardSchema } from './stat-card/StatCard';
import { Underline, underlineSchema } from './underline/Underline';
import { WordStagger, wordStaggerSchema } from './word-stagger/WordStagger';
import { chromaticAberration, chromaticAberrationSchema } from './transitions/chromatic-aberration/chromaticAberration';
import { clockWipe, clockWipeSchema } from './transitions/clock-wipe/clockWipe';
import { devicePullback, devicePullbackSchema } from './transitions/device-pullback/devicePullback';
import { glassWipe, glassWipeSchema } from './transitions/glass-wipe/glassWipe';
import { iris, irisSchema } from './transitions/iris/iris';
import { typeMask, typeMaskSchema } from './transitions/type-mask/typeMask';

export const ondaRegistry = {
  BarChart: { component: BarChart, schema: barChartSchema },
  BrowserFrame: { component: BrowserFrame, schema: browserFrameSchema },
  Confetti: { component: Confetti, schema: confettiSchema },
  CountUp: { component: CountUp, schema: countUpSchema },
  Cursor: { component: Cursor, schema: cursorSchema },
  DeviceFrame: { component: DeviceFrame, schema: deviceFrameSchema },
  DrawOn: { component: DrawOn, schema: drawOnSchema },
  IconPop: { component: IconPop, schema: iconPopSchema },
  MeshGradient: { component: MeshGradient, schema: meshGradientSchema },
  SlotMachineRoll: { component: SlotMachineRoll, schema: slotMachineRollSchema },
  StatCard: { component: StatCard, schema: statCardSchema },
  Underline: { component: Underline, schema: underlineSchema },
  WordStagger: { component: WordStagger, schema: wordStaggerSchema },
} as const;

export const ondaTransitions = {
  chromaticAberration: { factory: chromaticAberration, schema: chromaticAberrationSchema },
  clockWipe: { factory: clockWipe, schema: clockWipeSchema },
  devicePullback: { factory: devicePullback, schema: devicePullbackSchema },
  glassWipe: { factory: glassWipe, schema: glassWipeSchema },
  iris: { factory: iris, schema: irisSchema },
  typeMask: { factory: typeMask, schema: typeMaskSchema },
} as const;
